services:
  weather-station:
    container_name: weather-station
    image: ${REGISTRY}/weather-station:latest
    restart: unless-stopped
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime:ro