version: "3.9"
services:
  weather-station:
    container_name: weather-station
    image: bee:5001/weather-station:latest
    restart: unless-stopped
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime:ro